# DO NOT EDIT THIS FILE, IT IS GENERATED BY SETUP.PY
__version__ = "0.4.1"
git_branch = "dev"
git_commit_hash = "04a85184"
git_commit_date = "2022/02/11 16:13:02"
git_commit_count = 23
git_diff_name_only = ""

repo = "https://devops.momenta.works/Momenta/public/_git/run_in_build_env"
document = "https://confluence.momenta.works/x/HLc5Cw"


if __name__ == "__main__":
    for name, value in dict(locals()).items():
        if name.startswith("_") and name != "__version__":
            continue
        print(f"{name}: {value}")
